### PR TITLE
Auto Guilty commit search CSV generate

### PR DESCRIPTION
**Pull request by WeizhuoZhang-intel**
**Feature**: `report.py` will generate 2 files which are `guilty_commit_search_model_list.csv` and `guilty_commit_search_model_list.json`. Those files contain the following infomation

- **suite**: torchbench, huggingface, timm_models
- **model** name
- **scenario**: performance or accuracy
- **thread mode**: multiple or single
- **test kind**: crash, drop, fixed or improve
- **precision**

### CODE REVIEW

**Comment by WeizhuoZhang-intel** [comment]
Test Job:
image

**Comment by WeizhuoZhang-intel** [comment]
Fixed duplicate thread write issue in Excel
image

**Review by chuanqi129 — APPROVED** [review]
LGTM, does this PR also include the failure model list generate enhancement?

**Comment by WeizhuoZhang-intel** [comment]
> LGTM, does this PR also include the failure model list generate enhancement?

Do you mean csv or json file include all: crash, drop, improve and regression models? If that is the question, the answer is yes.

**Comment by WeizhuoZhang-intel** [comment]
> > > LGTM, does this PR also include the failure model list generate enhancement?
> > 
> > 
> > Do you mean csv or json file include all: crash, drop, improve and regression models? If that is the question, the answer is yes.
> 
> No, I mean the new request in yesterday meeting. Use the union model list of performance csv and accuracy csv to generate the failure model list.

Oh, it's not. It will be fixed by tomorrow.

**Pull request merged**
