### PR TITLE
Use N/A to indicate the accuracy failed, but perf didn't run case

### PR DESCRIPTION
**Pull request by WeizhuoZhang-intel**

### CODE REVIEW

**Comment by WeizhuoZhang-intel** [comment]
image

**Comment by chuanqi129** [comment]
3 questions,
- How about accuracy pass, but performance not run case?
- How about performance fail/pass, but accuracy not run case?
- Do we consider those N/A as failure when we generate new failure/fixed model list?

Suggest to get a union model lists of performance & accuracy original csv, and check model status in this union model list one-by-one.

**Comment by WeizhuoZhang-intel** [comment]
> 3 questions,
> 
> * How about accuracy pass, but performance not run case?
> * How about performance fail/pass, but accuracy not run case?
> * Do we consider those N/A as failure when we generate new failure/fixed model list?
> 
> Suggest to get a union model lists of performance & accuracy original csv, and check model status in this union model list one-by-one.

Hi @chuanqi129 

I have optimize this branch and solved all those questions.

- For 1 and 2, we both set it to N/A
- For 3, we add N/A to Excel failures sheet
image

- I generated a full model list which contains all the accuracy and perf info `all_model_list.csv`.
image

**Review by chuanqi129 — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
