### PR TITLE
add suite and thread for failure and regression

### PR DESCRIPTION
**Pull request by WeizhuoZhang-intel**

### CODE REVIEW

**Comment by WeizhuoZhang-intel** [comment]
**Excel part:**
image


image

**Comment by WeizhuoZhang-intel** [comment]
**HTML part**


image

**Review by chuanqi129 — APPROVED** [review]

**Comment by chuanqi129** [comment]
one small suggestion, for the model detail tables in excel, we may don't need add thread mode, because we already have 2 sheets to present the thread mode respectively.

**Comment by WeizhuoZhang-intel** [comment]
> one small suggestion, for the model detail tables in excel, we may don't need add thread mode, because we already have 2 sheets to present the thread mode respectively.

Good suggestion. This has been solved.

**Pull request merged**
