### PR TITLE
change cpp_wrapper according to PT PR #116115

### PR DESCRIPTION
**Pull request by zxd1997066**

### CODE REVIEW

**Comment by chuanqi129** [comment]
https://github.com/chuanqi129/inductor-tools/blob/main/scripts/cosim/inductor_single_run.sh please also update here

**Comment by zxd1997066** [comment]
> https://github.com/chuanqi129/inductor-tools/blob/main/scripts/cosim/inductor_single_run.sh please also update here

done

**Review by chuanqi129 — APPROVED** [review]
Please also update this part in your quantization test

**Comment by zxd1997066** [comment]
> Please also update this part in your quantization test

ok

**Pull request merged**
