### PR TITLE
Weizhuoz/passrate fix

### PR DESCRIPTION
**Pull request by WeizhuoZhang-intel**
### Passrate Formula
- `passrate = pass_models / total_models`
- `pass_models` is the number of models which pass performance and accuracy test
- `total_models` is same as the number of accuracy test models.

### `total_models` clarification:
1.  `total_models` is the number of `accuracy_results`, which is  refered to [pytorch/test-infra](https://github.com/pytorch/test-infra) repo and aligned with this repo
[Code snippet](https://github.com/pytorch/test-infra/blob/main/torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql#L117-L120):
```sql
    accuracy_results
    LEFT JOIN performance_results ON performance_results.name = accuracy_results.name
    AND performance_results.filename = accuracy_results.filename
    AND performance_results.workflow_id = accuracy_results.workflow_id
```

2. `model_fail_to_load` and `eager_fail_to_run` are excluded in `accuracy_results`
[Code snippet](https://github.com/pytorch/test-infra/blob/8f7a4bd4817527946575a5fff5c4fb45bb733493/torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql#L57-L58)
```sql
    AND accuracy != 'model_fail_to_load'
    AND accuracy != 'eager_fail_to_run'
```

### `pass_models` clarification:
1. If accuracy is `pass_due_to_skip`, no matter performance speed up is 0 or non-0, this case will be regarded as **PASS**.
2. Model could be regarded as **PASS** when performance is not 0 and accuracy is in this list `["pass", "pass_due_to_skip", "eager_variation"]`
Refer logic [Code snippet](https://github.com/pytorch/test-infra/blob/main/torchci/pages/benchmark/compilers.tsx#L94)
```javascript
export const PASSING_ACCURACY = ["pass", "pass_due_to_skip", "eager_variation"];
```

### Test results
- [Test job link:](https://inteltf-jenk.sh.intel.com/user/weizhuo/my-views/view/weizhuoz_view/job/inductor_job_result_compare_zwz/31/)
- **Before**
image
- **After**
image

### CODE REVIEW

**Comment by chuanqi129** [comment]
What's the effect of this change?

**Comment by WeizhuoZhang-intel** [comment]
@chuanqi129 .Please ignore this,  because at very early stage, we talk about use a new passrate formula to show. But seems it is not needed.

**Comment by WeizhuoZhang-intel** [comment]
> Can we keep original passrate and add a new passrate with the new calculate method?

Sure. Is it ok to add a new table for this new passrate? Or any other suggestions?

**Comment by chuanqi129** [comment]
> > Can we keep original passrate and add a new passrate with the new calculate method?
> 
> Sure. Is it ok to add a new table for this new passrate? Or any other suggestions?

New table is good

**Comment by WeizhuoZhang-intel** [comment]
Hi @chuanqi129 ,
The new table is done:
image

**Review by chuanqi129 — APPROVED** [review]

**Pull request merged**
